#################################
#             SLogin            #
#         Author _Serafin       #
#################################

# The language settings file contains in-game messages
# Languages available: en_US (English), pl_PL (Polish)
Language:
  # Player see the message in his language
  Auto: true
  # Console messages and player messages if Auto is disabled
  Default: en_US

# The place where the data will be saved
# Choose between FLAT and MYSQL
DataType: FLAT

# Fill only if you chose MYSQL data type
MySQL:
  Host: "localhost"
  Port: 3306
  User: "root"
  Pass: ""
  DataBase: "slogin"
  Properties: "useSSL=false&autoReconnect=true"

# One IP address cannot have more than this number of accounts
MaxAccountsPerIP: 2

Messages:
  # Shows chat messages on join
  ChatMessages: true
  # Shows title messages on join
  # Enable only if your server version is 1.11 or newer
  TitleMessages: true

# Allowed commands when you are not logged in
AllowedCommands:
  - l
  - login
  - reg
  - register

# Set minimum and maximum password length
Password:
  min-length: 5
  max-length: 20

# Informs every player on login that its email is not set
EmailNotification: true

# Time to log in (in seconds)
# 0 -> disabled
LoginTimeout: 30

# Captcha - checking starts when the player enters the server
Captcha:
  # Verify new player who is not registered
  OnRegister: false
  # Verify player who is registered
  OnLogin: false

# Kick the player after entering the wrong password
KickOnWrongPassword: true