name: SLogin
version: 1.7.1
author: _Serafin
description: Plugin for the login system
main: me.serafin.slogin.SLogin
load: STARTUP
commands:
  register:
    description: Register new player
    permission: slogin.register
    aliases: [ reg ]
  login:
    description: Sign in to the server
    permission: slogin.login
    aliases: [ l ]
  changepassword:
    description: Change your password
    permission: slogin.changepassword
    aliases: [ cp, changepass ]
  email:
    description: Change and set player's email
    permission: slogin.email
    aliases: [ mail ]
  slogin:
    description: Admin commands
    permission: slogin.admin
    aliases: [ sl, slogin ]
permissions:
  slogin.register:
    default: true
    description: allows you to use the login command
  slogin.login:
    default: true
    description: allows you to use the register command
  slogin.changepassword:
    default: true
    description: allows you to use the password change command
  slogin.email:
    default: true
    description: allows you to use the email command
  slogin.admin:
    default: false
    description: allows you to use admin's commands
  slogin.*:
    description: allows you to use all commands
    children:
      slogin.register: true
      slogin.login: true
      slogin.changepassword: true
      slogin.email: true
      slogin.admin: true